language: php
php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

script:
  - phpunit --coverage-clover=coverage.xml

before_install:
  - pip install --user codecov
  
after_success:
  - codecov
