language: php
php:
  - 5.6
  - nightly

script:
  - phpunit --coverage-clover=phpstream.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover phpstream.clover
  - rm -f phpstream.clover ocular.phar

