language: php

matrix:
  include:
    - php: 7.1
      env:
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=./vendor/bin/phpunit
    - php: 7.2
      env:
        - PHPUNIT_BIN=./vendor/bin/phpunit
        - WITH_BENCHMARK=true
    - php: 7.3
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit
    - php: 7.4
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - WITH_CODECOV=true
        - PHPUNIT_BIN=phpunit
    - php: nightly
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit

script:
  - test -z "${CLEAR_PHP_UNIT}" || composer remove --dev "phpunit/phpunit"
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - test -z "${WITH_BENCHMARK}" || bash ./benchmark/benchmark.sh
  - ${PHPUNIT_BIN} --coverage-clover coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - test -z "${WITH_CODECOV}" || codecov --branch php-7
