language: php

php:
  - '8.0'
  - '8.1'
  - '8.2'
  - hhvm
  - nightly

matrix:
  include:
    - php: 8.0
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit
        - WITH_CODECOV=true
    - php: 8.1
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit
        - WITH_CODECOV=true
    - php: 8.2
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit
        - WITH_CODECOV=true
    - php: hhvm
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit
        - WITH_CODECOV=true
    - php: nightly
      env:
        - CLEAR_PHP_UNIT=true
        - WITH_BENCHMARK=true
        - PHPUNIT_BIN=phpunit

script:
  - test -z "${CLEAR_PHP_UNIT}" || composer remove --dev "phpunit/phpunit"
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
  - test -z "${WITH_BENCHMARK}" || bash ./benchmark/benchmark.sh
  - ${PHPUNIT_BIN} --coverage-clover coverage.xml

before_install:
  - pip install --user codecov

after_success:
  - test -z "${WITH_CODECOV}" || codecov
